sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hRjQFvzD5PX1xWPhSdN7p5KvsN4AT3pKMkTj/YC04XibRr1ms6vjhNeK06v1x7yGAUj3jDI4EyC9oMNPz/irLt9tHvZxOm21gts1eqRWSqP0DJwcXGzksM296TA/hRcMjufpbdZjaZrsoNv1ul96ZotzO3wkcnJi8noXnN8nIFwnqrZ0KjGfvZc1uiWjcPabp7WELOABXO4f4G7+BKWXP1ZzQbQAdeieIxEjlsyXr2IoNNoIu8IMa7c+fsm4p8iN8vKJGTCjPNqeGNTQXTegLdaWkhJJQgoHHv7tdxJJMLztYzB1G0Fw/NUxbLE+hGT5V7uTiRbS9mcbCibI3/6cmFDYuON+kDguBrchU7pJenDJXebfdQyK2jdo2t5GKbDE1+ggVRxvrqe+lUClSBxdT9z9WoL/hhybJf8YRe+5/a9R0oSp3IY3VTJ9DR9PuIkJMt3M0RUw6CWyw0ezzsqlgUMFmxvUo8XndR2xb5qx1yxZeMeSmrzhlhi3eNvwf+NbMBr0F6VtoejMFrioybzIt9u1kMwt6uA9dPrf0BAIOJUMyKTVTJ4+6S8IOTgRGs8Q3LlkafDEUVXUV2/0BFIGcL0F85V7u9zZvbdxY/zAu7rDVWLPuVyC5cKOxDHCLv8t6opf3aDc47Q7fad5vyQFg80BYVxPOXpx91GlH/elHzQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Monsieur-Madame-and-B-b----Complete_3926
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy